# Generated by Django 4.0.6 on 2022-07-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=10)),
                ('hora', models.CharField(max_length=5)),
                ('apellido', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('dni', models.CharField(max_length=8)),
                ('sexo', models.CharField(blank=True, max_length=20)),
                ('domicilio', models.CharField(blank=True, max_length=150)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('barrio', models.CharField(blank=True, max_length=100)),
                ('region_satinaria', models.CharField(blank=True, max_length=100)),
                ('motivo_consulta', models.CharField(blank=True, max_length=50)),
                ('evaluacion', models.CharField(blank=True, max_length=300)),
                ('tratamiento_psicofarm', models.CharField(blank=True, max_length=300)),
                ('internacion', models.CharField(blank=True, max_length=12)),
                ('derivacion', models.CharField(blank=True, max_length=2)),
                ('auxilio', models.CharField(blank=True, max_length=100)),
                ('intervencion', models.CharField(blank=True, max_length=100)),
                ('profesionales', models.TextField()),
            ],
        ),
    ]
